apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
  labels:
    app: zigbee2mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zigbee2mqtt
  template:
    metadata:
      labels:
        app: zigbee2mqtt
        sentinel: "1"
    spec:
      containers:
        - name: zigbee2mqtt
          image: koenkk/zigbee2mqtt:1.33.2
          env:
            - name: TZ
              value: Europe/Zurich
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
          volumeMounts:
            - name: dev-usb0
              mountPath: /dev/ttyACM0
            - name: zigbee2mqttdata
              mountPath: /app/data
            - name: runudev-local
              mountPath: /run/udev
          securityContext:
            privileged: true
      volumes:
        - name: dev-usb0
          hostPath:
            path: /dev/ttyACM0
        - name: zigbee2mqttdata
          hostPath:
            path: /home/he/zigbee2mqtt
        - name: runudev-local
          hostPath:
            path: /run/udev
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeName: raspi5b1
      securityContext: {}

---
apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
#   labels:
#     app: zigbee2mqttassistant
#     kubernetes.io/name: zigbee2mqttassistant
spec:
  type: NodePort
  selector:
    app: zigbee2mqtt
  ports:
    - name: zigbee2mqttui
      protocol: TCP
      port: 31000
      targetPort: 8080
      nodePort: 31000
  externalTrafficPolicy: Cluster