apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  labels:
    app: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
        sentinel: "1"
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:{{ .Values.mosquitto.image.tag }}
          ports:
            - containerPort: 1883
              protocol: TCP
            - containerPort: 9001
              protocol: TCP
            - containerPort: 8883
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: mosquitto-conf
              mountPath: /mosquitto/config
            - name: mosquitto-data
              mountPath: /mosquitto/data
            - name: mosquitto-log
              mountPath: /mosquitto/log
            - name: localtime
              mountPath: /etc/localtime
      volumes:
        - name: mosquitto-conf
          hostPath:
            path: /home/he/mosquitto/config
        - name: mosquitto-data
          hostPath:
            path: /home/he/mosquitto/data
        - name: mosquitto-log
          hostPath:
            path: /home/he/mosquitto/log
        - name: localtime
          hostPath:
            path: /etc/localtime
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  labels:
    app: mosquitto
    kubernetes.io/name: mosquitto
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31612