apiVersion: apps/v1
kind: Deployment
metadata:
  name: openthread-border-router
  labels:
    app: openthread-border-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openthread-border-router
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: openthread-border-router
    spec:
      containers:
        - name: openthread-border-router
          image: openthread/border-router:{{ .Values.thread.otbr.image.tag }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OT_RCP_DEVICE
              value: spinel+hdlc+uart:///dev/ttyACM0?uart-baudrate=1000000
            - name: OT_INFRA_IF
              value: {{ .Values.thread.infraInterface | quote }}
            - name: OT_REST_LISTEN_ADDR
              value: "$(HOST_IP)"
            - name: OT_THREAD_IF
              value: wpan0
            - name: OT_WEB_LISTEN_PORT
              value: "8082"
            - name: OT_LOG_LEVEL
              value: "5"
          securityContext:
            privileged: true
          volumeMounts:
            - name: zbt2-thread-radio
              mountPath: /dev/ttyACM0
            - name: tun
              mountPath: /dev/net/tun
            - name: otbr-data
              mountPath: /data
      volumes:
        - name: zbt2-thread-radio
          hostPath:
            path: /dev/serial/by-id/usb-Nabu_Casa_ZBT-2_1CDBD45F0928-if00
            type: CharDevice
        - name: tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
        - name: otbr-data
          hostPath:
            path: /home/he/otbr
            type: Directory
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: floor
                    operator: In
                    values:
                      - eg
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: openthread-border-router
spec:
  selector:
    app: openthread-border-router
  ports:
    - name: rest
      protocol: TCP
      port: 8081
      targetPort: 8081
