apiVersion: apps/v1
kind: Deployment
metadata:
  name: changedetectionio
  labels:
    app: changedetectionio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: changedetectionio
  template:
    metadata:
      labels:
        app: changedetectionio
        sentinel: "1"
    spec:
      containers:
      - name: changedetectionio
        image: ghcr.io/dgtlmoon/changedetection.io:{{ .Values.changedetectionio.image.tag }}
        env:
        - name: TZ
          value: Europe/Zurich
        securityContext:
          privileged: true
        resources:
          limits:
            memory: "500Mi"
          requests:
            memory: "300Mi"
        volumeMounts:
        - name: changedetectionio
          mountPath: /datastore
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
        - name: changedetectionio
          hostPath:
            path: /home/he/changedetectionio
        - name: localtime
          hostPath:
            path: /etc/localtime
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: floor
                operator: In
                values:
                - eg
      restartPolicy: Always
      strategy:
        type: Recreate
      terminationGracePeriodSeconds: 30
      hostNetwork: false
      dnsPolicy: ClusterFirstWithHostNet
      securityContext: {}

---
apiVersion: v1
kind: Service
metadata:
  name: changedetectionio
spec:
  selector:
    app: changedetectionio
  ports:
  - name: http
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: changedetectionio-nodeport-service
spec:
  type: NodePort
  selector:
    app: changedetectionio
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30010