apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hass
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pantry-api
            port:
              number: 8080
  - host: {{ .Values.hostnamepantry }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 80
  - host: {{ .Values.hostnamepantryapi }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pantry-api
            port:
              number: 8080
  - host: {{ .Values.hostnamehomeassistant }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant
            port:
              number: 8123
  tls:
    - secretName: my-host-tls
      hosts:
        - {{ .Values.hostname }}
    - secretName: pantryha-tls
      hosts:
        - {{ .Values.hostnamepantry }}
    - secretName: api-pantryha-tls
      hosts:
        - {{ .Values.hostnamepantryapi }}
    - secretName: homeassistant-tls
      hosts:
        - {{ .Values.hostnamehomeassistant }}